### ISSUE TITLE
Documentation on cross-compilation

### ISSUE THREAD

**Issue by goloroden** [marcboeker/go-duckdb#279]
Today, I'd like to ask for a small feature request, which – I think – could be useful to more people than just me.

It's about cross-compiling Go programs which shall use DuckDB. While building a binary for the platform you're developing on is pretty simple, doing the same with cross-compilation is not.

Given that there are three major operating systems these days (macOS, Linux, Windows), and two CPU architectures (x86-64 and ARM), you end up with quite a number of combinations: You essentially have six combinations as development base, and you have six combinations you might want to build.

E.g.:

- Build for macOS / ARM on a Linux / x86-64 machine.
- Build for Windows / x86-64 on a macOS / arm machine.
- And so on …

Effectively, this is 36 combinations in total.

Now here's my question: Since I find it pretty difficult to figure out how to cross-compile, would it maybe be possible to add information on this to the documentation of this module? I think that it doesn't need an example per combination, but having some general guidelines or tips would already be helpful (or even a link to a page which explains it in more detail).

What do you think of this?

PS: If someone is able to provide the commands, I'd be more than happy to work on the documentation and submit a PR. It's just that I don't know how to do it myself.

**Comment by marcboeker** [comment]
@goloroden Thanks for bringing this up. Cross-compiling is a total pain. What could make sense is an issue where we first collect all the cross-compiling combinations we have working so far. Then we can start generating a kind of matrix from it with source and destination and which toolchain to use.

Starting with macOS we could use the [approach](https://github.com/marcboeker/go-duckdb/issues/243#issuecomment-2204483650) I've commented in an earlier issue you have opened.

With linux as source we could use the compile chain from the Github runners (need to figure out what the have pre-installed) and the commands from the `Makefile`.

From and to Windows: @taniabogatsch is currently working on a Windows build. But I have no access to Windows to test anything. And I'm still confused about Mingw32, Msys2, Cygwin...

**Comment by goloroden** [comment]
Okay, I'll start collecting things here:

### From macOS (ARM) to Linux (x86)

```
$ brew tap messense/macos-cross-toolchains
$ brew install x86_64-unknown-linux-gnu
$ CC="x86_64-linux-gnu-gcc" CXX="x86_64-linux-gnu-g++" CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build examples/simple.go 
```

**Comment by goloroden** [comment]
@marcboeker I have collected what I have so far, do you maybe have other ones you can contribute?

**Comment by yusufozturk** [comment]
I am trying to build it on windows 10:

```
go build -tags="no_duckdb_arrow"
# win-duckdb
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Yusuf-I9/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.2/deps/windows_amd64\libduckdb.a(ub_duckdb_main_extension.cpp.obj):ub_duckdb_main_extension.cpp:(.rdata$_ZTVN14duckdb_httplib8DataSink19data_sink_streambufE[_ZTVN14duckdb_httplib8DataSink19data_sink_streambufE]+0x38): undefined reference to `std::basic_streambuf<char, std::char_traits<char> >::seekpos(std::fpos<_Mbstatet>, std::_Ios_Openmode)'
collect2.exe: error: ld returned 1 exit status
```

I tried different things but it doesn't work.
I am able to build duckdb from the source. But somehow I can not build your example.

**Comment by goloroden** [comment]
@yusufozturk What happens if you simply run:

```shell
$ go build .
```

Does this create an executable for Windows, which includes DuckDB?

**Comment by yusufozturk** [comment]
@goloroden no, same error.

I tried a lot of different things, but nothing worked for me.

@taniabogatsch I dont think #248 solves all the issues. Or maybe @JAicewizard can share a step by step process to help us :)

**Comment by goloroden** [comment]
@yusufozturk Anyway: Thanks for trying it out and giving instant feedback 😊

**Comment by yusufozturk** [comment]
![image](https://github.com/user-attachments/assets/aceb8b74-ffac-479d-bdbb-eefb8e10afd8)

Okay somehow it works now. I can build and debug on VS Code, but only with  -tags="no_duckdb_arrow". But I have no idea what fixed the problem because I tried a lot of different things.

I will try to replicate the success on a clean Windows machine and I will create a documentation for my team. I can share the same documentation here if I can make it again.

**Comment by JAicewizard** [comment]
> I am trying to build it on windows 10:
> 
> ```
> go build -tags="no_duckdb_arrow"
> # win-duckdb
> C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Yusuf-I9/go/pkg/mod/github.com/marcboeker/go-duckdb@v1.8.2/deps/windows_amd64\libduckdb.a(ub_duckdb_main_extension.cpp.obj):ub_duckdb_main_extension.cpp:(.rdata$_ZTVN14duckdb_httplib8DataSink19data_sink_streambufE[_ZTVN14duckdb_httplib8DataSink19data_sink_streambufE]+0x38): undefined reference to `std::basic_streambuf<char, std::char_traits<char> >::seekpos(std::fpos<_Mbstatet>, std::_Ios_Openmode)'
> collect2.exe: error: ld returned 1 exit status
> ```
> 
> I tried different things but it doesn't work. I am able to build duckdb from the source. But somehow I can not build your example.

I can reproduce this on linux with mingw, I don't know how to fix it though. One possibility is that the gcc version on github CI is different from that on your (and my) machine, leading to different stdc++ being used (https://stackoverflow.com/questions/73261554/sfml-undefined-reference-to-stdbasic-streambuf). I don't know how to fix this easily, besides setting your mingw version to be the same as on github CI. You could also try running `deps.windows.amd64` to create the dependencies specifically for your system and see if that works.

**Comment by taniabogatsch** [comment]
> Edit: VS Code debug works perfectly. Building is also okay. Binary is generated. But binary is crashing when it tries to load DuckDB. At this line:
db, err := sql.Open("duckdb", "")
There is no error or panic. Just stops working at this line.

I remember having seen this before in one of the issues... 🤔 

> I dont think https://github.com/marcboeker/go-duckdb/pull/248 solves all the issues.

I agree, the shipped Windows build currently provides a solution for one(?) workflow/mingw version? But I don't have enough experience with Windows to know how to fix this for the pre-build library...

Also, it might be worth bundling the different issues and solutions on Windows into a discussion. Similar to this issue being a collection of knowledge on cross compilation.

**Comment by y-bruin** [comment]
We have integrated DuckDB with the Bruin CLI and successfully built it for Linux and macOS. However, it’s not working as expected on Windows. Do you think it's possible to to build windows binary at this moment ?

goreleaser config 
```
project_name: bruin
version: 2
dist: ./.cache/goreleaser
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go mod tidy
builds:
  # - id
  - id: bruin-windows-amd64
    binary: bruin
    main: ./
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe
      - -tags="no_duckdb_arrow"
    ldflags:
      - -s -w -X main.version={{ .Env.VERSION }}"
      - "-linkmode=external"
archives:
  - format: tar.gz
    builds:
      # - bruin-linux-arm64
      # - bruin-linux-amd64
      # - bruin-darwin
      - bruin-windows-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```

error
```
~/W/b/bruin (main)> docker run -it --rm -e VERSION=0.0.1  -v $(pwd):/src -w /src goreleaser/goreleaser-cross:v1.22 release --snapshot --clean
  • skipping announce, publish and validate...
  • loading environment variables
  • getting and validating git state
    • git state                                      commit=5c607a53e784f008c8bb8671a5cfcd97df453a94 branch=main current_tag=v0.11.42 previous_tag=v0.11.41 dirty=true
    • pipe skipped                                   reason=disabled during snapshot mode
  • parsing tag
  • setting defaults
  • snapshotting
    • building snapshot...                           version=0.11.42-SNAPSHOT-5c607a5
  • running before hooks
    • running                                        hook=go mod tidy
    • took: 20s
  • checking distribution directory
    • cleaning ./.cache/goreleaser
  • setting up metadata
  • writing release metadata
  • loading go mod information
  • build prerequisites
  • building binaries
    • building                                       binary=.cache/goreleaser/bruin-windows-amd64_windows_amd64_v1/bruin.exe
    • took: 46s
  ⨯ release failed after 1m7s                        error=failed to build for windows_amd64_v1: exit status 1: # github.com/bruin-data/bruin
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lRstrtmgr
collect2: error: ld returned 1 exit status
```

Does anyone know what might be wrong with the Windows build? You can find our goreleaser and github action workflow [here](https://github.com/bruin-data/bruin/blob/main/.goreleaser.yaml).
